=== Open-Attestation/open-attestation/src/4.0/schema/schema.json
{
  "title": "OpenAttestation v4.0 Schema",
  "$id": "https://schemata.openattestation.com/com/openattestation/4.0/alpha-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "@context": {
      "description": "Used to define the short-hand names that are used throughout a JSON-LD document.",
      "type": ["object", "string", "array", "null"]
    },
    "id": {
      "description": "Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.",
      "type": "string",
      "format": "uri"
    },
    "type": {
      "description": "Used to set the data type of a node or typed value.",
      "type": ["string", "null", "array"]
    },
    "credentialSchema": {
      "type": "object",
      "properties": {
        "id": { "$ref": "#/definitions/id" },
        "type": { "$ref": "#/definitions/type" }
      },
      "description": "A data schema that provide verifiers with enough information to determine whether the provided data conforms to the provided schema(s). More information in https://www.w3.org/TR/vc-data-model-2.0/#data-schemas"
    },
    "credentialSubject": {
      "type": "object",
      "properties": {
        "id": { "$ref": "#/definitions/id" },
        "type": { "$ref": "#/definitions/type" }
      },
      "description": "A verifiable credential contains claims about one or more subjects. More information in https://www.w3.org/TR/vc-data-model-2.0/#credential-subject"
    },
    "termsOfUse": {
      "type": "object",
      "properties": {
        "type": { "$ref": "#/definitions/type" }
      }
    },
    "evidence": {
      "type": "object",
      "properties": {
        "type": { "$ref": "#/definitions/type" }
      }
    },
    "proof": {
      "type": "object",
      "properties": {
        "type": { "$ref": "#/definitions/type", "examples": ["OpenAttestationMerkleProofSignature2018"] },
        "proofPurpose": { "type": "string", "enum": ["assertionMethod"] },
        "targetHash": { "type": "string" },
        "proofs": { "type": "array", "items": { "type": "string" } },
        "merkleRoot": { "type": "string" },
        "salts": { "type": "string" },
        "privacy": {
          "type": "object",
          "properties": { "obfuscated": { "type": "array", "items": { "type": "string" } } }
        },
        "key": { "type": "string" },
        "signature": { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "@context": { "$ref": "#/definitions/@context" },
    "id": { "$ref": "#/definitions/id" },
    "type": { "$ref": "#/definitions/type", "examples": ["VerifiableCredential", "OpenAttestationCredential"] },
    "credentialSchema": {
      "anyOf": [
        { "$ref": "#/definitions/credentialSchema" },
        { "type": "array", "items": { "$ref": "#/definitions/credentialSchema" } }
      ]
    },
    "validFrom": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when this credential becomes valid",
      "examples": ["2024-03-08T12:00:00+08:00"]
    },
    "validUntil": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when this credential expires",
      "examples": ["2024-03-27T12:00:00+08:00"]
    },
    "name": {
      "type": "string",
      "description": "Human readable name of this credential"
    },
    "issuer": {
      "oneOf": [
        { "type": "string" },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uri",
              "description": "URI when dereferenced, results in a document containing machine-readable information about the issuer that can be used to verify the information expressed in the credential. More information in https://www.w3.org/TR/vc-data-model/#issuer"
            },
            "type": { "$ref": "#/definitions/type", "examples": ["OpenAttestationIssuer"] },
            "name": {
              "type": "string",
              "description": "Issuer's name"
            },
            "identityProof": {
              "type": "object",
              "properties": {
                "identityProofType": {
                  "type": "string",
                  "enum": ["DNS-TXT", "DNS-DID", "DID"]
                },
                "identifier": {
                  "type": "string",
                  "description": "Identifier to be shown to end user upon verifying the identity"
                }
              },
              "required": ["identityProofType", "identifier"],
              "additionalProperties": false
            }
          },
          "required": ["id"]
        }
      ]
    },
    "credentialStatus": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "URI to the status of the credential as explained by https://www.w3.org/TR/vc-data-model/#status",
          "examples": ["https://ocsp-sandbox.openattestation.com"]
        },
        "type": { "$ref": "#/definitions/type", "examples": ["OpenAttestationOcspResponder"] }
      },
      "additionalProperties": false
    },
    "renderMethod": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
          "description": "URL of a decentralised renderer to render this document",
          "examples": ["https://demo-renderer.openattestation.com"]
        },
        "type": { "$ref": "#/definitions/type", "examples": ["OpenAttestationEmbeddedRenderer"] },
        "name": {
          "type": "string",
          "description": "Template name to be use by template renderer to determine the template to use"
        }
      },
      "required": ["id", "name"]
    },
    "credentialSubject": {
      "anyOf": [
        { "$ref": "#/definitions/credentialSubject" },
        { "type": "array", "items": { "$ref": "#/definitions/credentialSubject" } }
      ]
    },
    "termsOfUse": {
      "anyOf": [
        { "$ref": "#/definitions/termsOfUse" },
        { "type": "array", "items": { "$ref": "#/definitions/termsOfUse" } }
      ]
    },
    "evidence": {
      "anyOf": [
        { "$ref": "#/definitions/evidence" },
        { "type": "array", "items": { "$ref": "#/definitions/evidence" } }
      ]
    },
    "proof": {
      "anyOf": [{ "$ref": "#/definitions/proof" }, { "type": "array", "items": { "$ref": "#/definitions/proof" } }]
    }
  },
  "required": ["@context", "type", "issuer", "credentialSubject"]
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-status-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "CredentialStatusList2017": "https://example.org/examples#CredentialStatusList2017"
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  },
  "credentialStatus": {
    "id": "did:example:status",
    "type": "CredentialStatusList2017"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-issuer-description-language-en-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": {
    "id": "did:example:issuer",
    "description": {
      "@value": "An Example Issuer",
      "@language": "en"
    }
  },
  "credentialSubject": {
    "id": "did:example:subject"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-single-id-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://www.w3.org/ns/credentials/examples/v2"
  ],
  "type": [
    "VerifiableCredential"
  ],
  "id": "https://example.org/credentials/1",
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "description": "A single id test for VC 2.0"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-type-mapped-url-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "ExampleTestCredential": "https://example.org/#ExampleTestCredential"
    }
  ],
  "type": [
    "VerifiableCredential",
    "ExampleTestCredential"
  ],
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-evidences-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "DocumentVerification2018": "https://example.org/examples#DocumentVerification2018"
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  },
  "evidence": [
    {
      "type": "DocumentVerification2018"
    },
    {
      "type": "DocumentVerification2018"
    }
  ]
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-type-urls-order-1-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": [
    "https://example.org/#ExampleCredential1",
    "https://example.org/#ExampleCredential2",
    "VerifiableCredential"
  ],
  "validFrom": "2023-02-23T21:41:38Z",
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-schema-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": [
    "VerifiableCredential"
  ],
  "credentialSchema": {
    "type": "https://example.org/#ExampleTestSuiteSchema",
    "id": "did:example:schemas/1"
  },
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  }
}

=== Open-Attestation/open-attestation/test/fixtures/w3c-inputs/credential-termsofuse-ok.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "OdrlPolicy2017": "https://example.org/examples#OdrlPolicy2017"
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:example:issuer",
  "credentialSubject": {
    "id": "did:example:subject"
  },
  "termsOfUse": {
    "type": "OdrlPolicy2017"
  }
}
